<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 16.06.18
 * Time: 7:58
 */

namespace Html\Dz\Render;


class RenderSimple extends AbstractRender
{
    public function renderObject(ITag $obj):string
    {
        $str = parent::renderObject($obj); // TODO: Change the autogenerated stub
        
        return "$str />";
    }
}