<?php
/**
 * Created by PhpStorm.
 * User: alex
 * Date: 15.06.18
 * Time: 11:45
 */

namespace MyHtml\Form;


use MyHtml\Tag;

class Form extends Tag
{
    public function __construct()
    {
        $this->content = [];
        $this->tagName = 'form';
    }

    protected function putContent($content)
    {
        $this->content[] = $content; // TODO: Change the autogenerated stub
    }
    
    protected function getContent()
    {
        $result = '';
        foreach($this->content as $value) {
            $result .= (string)$value . PHP_EOL;
        }

        return $result;
    }

    protected function getPossibleAttributes():array
    {
        return [
            'name',
            'autocomplete',
            'novalidate',
            'accept-charset',
            'action',
            'method',
            'enctype',
            'target',
        ];
    }

    protected function getRequiredAttributes():array
    {
        return [
            'action',
            'method',
            'enctype',
            'target',
        ];
    }

    protected function getDefaultAttributes():array
    {
        return [
            'method' => 'GET',
            'enctype' => 'application/x-www-form-urlencoded',
            'target' => '_self',
        ];
    }
}